/** 返回 Harness 业务控制面交互脚本。 */
export function adminScript(): string {
  return `const base=location.pathname.replace(/[/]$/,'');let token=sessionStorage.getItem('workorderAdminToken')||'';let state;
const byId=id=>document.getElementById(id);const text=(id,value)=>{byId(id).textContent=String(value??'')};
function messageContent(id,value){const target=byId(id);target.replaceChildren();const pattern=new RegExp('(\\[#\\d+\\]\\(https?:\\/\\/[^\\s)]+\\))','g');const linkPattern=new RegExp('^\\[#(\\d+)\\]\\((https?:\\/\\/[^\\s)]+)\\)$');String(value??'').split(pattern).forEach(part=>{const match=linkPattern.exec(part);if(!match){target.appendChild(document.createTextNode(part));return}const link=document.createElement('a');link.href=match[2];link.target='_blank';link.rel='noopener noreferrer';link.textContent='#'+match[1];target.appendChild(link)})}
const headers=()=>({'authorization':'Bearer '+token,'content-type':'application/json'});let previewId='';
function tokenView(){byId('adminToken').value=token;text('tokenState',token?'已保存到当前会话':'未保存管理令牌')}
async function request(path,options={}){if(!token)throw new Error('请先在设置页保存管理令牌');const response=await fetch(base+path,{...options,headers:headers()});const raw=await response.text();let data;try{data=raw?JSON.parse(raw):{}}catch{throw new Error(response.status===404?'接口地址不存在，请刷新页面后重试':'服务返回了非 JSON 响应')}if(!response.ok){if(response.status===401){sessionStorage.removeItem('workorderAdminToken');token='';tokenView()}throw new Error(data.error||'请求失败')}return data}
function rows(id,items,fields){const body=byId(id);body.replaceChildren();const appendRow=values=>{const row=document.createElement('tr');values.forEach(value=>{const cell=document.createElement('td');cell.textContent=String(value??'');if(!items.length){cell.colSpan=fields.length;cell.className='empty'}row.appendChild(cell)});body.appendChild(row)};if(!items.length){appendRow(['暂无记录']);return}items.forEach(item=>appendRow(fields.map(field=>field(item))))}
function reviewRows(items){const body=byId('reviewRows');body.replaceChildren();if(!items.length){const row=document.createElement('tr');const cell=document.createElement('td');cell.colSpan=5;cell.className='empty';cell.textContent='暂无记录';row.appendChild(cell);body.appendChild(row);return}items.forEach(item=>{const row=document.createElement('tr');row.className='review-row';[item.createdAt,item.startDate+' 至 '+item.endDate,item.status,item.expiresAt].forEach(value=>{const cell=document.createElement('td');cell.textContent=value;row.appendChild(cell)});const cell=document.createElement('td');cell.className='review-actions';const button=document.createElement('button');button.type='button';button.className='detail-button';button.textContent='查看详情';button.onclick=event=>{event.stopPropagation();loadReviewDetail(item.id,button)};const resend=document.createElement('button');resend.type='button';resend.className='resend-button';resend.textContent='再次发送';resend.onclick=event=>{event.stopPropagation();resendReview(item.id,resend)};row.onclick=()=>loadReviewDetail(item.id,button);cell.append(button,resend);row.appendChild(cell);body.appendChild(row)})}
async function resendReview(id,button){if(!confirm('确认再次发送该复核结果至 POPO？'))return;const original=button.textContent;button.disabled=true;button.textContent='发送中…';text('reviewActionMessage','正在发送复核结果…');try{const data=await request('/api/admin/previews/'+encodeURIComponent(id)+'/resend',{method:'POST',body:JSON.stringify({confirmation:'确认再次发送复核结果'})});text('reviewActionMessage',data.message)}catch(error){text('reviewActionMessage',error.message)}finally{button.disabled=false;button.textContent=original}}
async function loadReviewDetail(id,button){const buttons=document.querySelectorAll('.detail-button');buttons.forEach(item=>item.disabled=true);if(button)button.textContent='加载中…';text('reviewDetailSummary','正在加载…');text('reviewDetailContent','');byId('reviewDetailContent').scrollIntoView({behavior:'smooth',block:'nearest'});try{const data=await request('/api/admin/previews/'+encodeURIComponent(id));text('reviewDetailSummary',data.startDate+' 至 '+data.endDate+'｜'+data.status+'｜巡检工单 '+data.scanned+' 个｜待完善项 '+data.violationCount+' 项');messageContent('reviewDetailContent',data.message||'本次复核没有待发送内容。')}catch(error){text('reviewDetailSummary','加载失败');text('reviewDetailContent',error.message)}finally{buttons.forEach(item=>item.disabled=false);if(button)button.textContent='查看详情'}}
function configured(id,value){text(id,value?'已配置':'未配置');byId(id).className=value?'ok':'warn'}
function render(data){state=data;text('health',data.healthy?'运行正常':'服务异常');text('schedule',data.settings.scheduleEnabled?'已启用':'未启用');text('autoSend',data.settings.automaticSendEnabled?'已启用':'未启用');text('webhookProcessing',data.settings.webhookProcessingEnabled?'已启用':'未启用');text('runCount',data.runs.length);byId('scheduleEnabled').checked=data.settings.scheduleEnabled;byId('automaticSendEnabled').checked=data.settings.automaticSendEnabled;byId('webhookProcessingEnabled').checked=data.settings.webhookProcessingEnabled;configured('gcpConfigured',data.configured.gcpUserKey);configured('popoConfigured',data.configured.popoWebhook);configured('webhookConfigured',data.configured.webhookEntry);configured('adminConfigured',data.configured.adminToken);text('projectConfig','项目映射：'+Object.entries(data.projects).map(([name,id])=>name+' '+id).join('；')+'。完成状态 ID：'+data.completedStatusId);rows('runs',data.runs,[x=>x.createdAt,x=>x.type,x=>x.startDate+' 至 '+x.endDate,x=>x.scanned,x=>x.violationCount,x=>x.status]);rows('events',data.webhooks,[x=>x.createdAt,x=>x.traceId,x=>x.issueId,x=>x.projectId,x=>x.status,x=>x.attempts,x=>x.error||'']);reviewRows(data.previews)}
async function load(){if(!token){text('globalMessage','请前往设置页输入管理令牌');return}try{render(await request('/api/admin/status'));text('globalMessage','')}catch(error){text('globalMessage',error.message)}}
const popoStatus={pending:'待发送',sending:'发送中',partial:'部分成功',sent:'已发送',failed:'发送失败','dead-letter':'停止重试'};
function popoRows(items){const body=byId('popoRows');body.replaceChildren();if(!items.length){const row=document.createElement('tr');const cell=document.createElement('td');cell.colSpan=7;cell.className='empty';cell.textContent='暂无消息记录';row.appendChild(cell);body.appendChild(row);return}items.forEach(item=>{const row=document.createElement('tr');[item.createdAt,item.sourceType,popoStatus[item.status]||item.status,item.sentChunkCount+'/'+item.chunkCount,item.attempts,item.error||''].forEach(value=>{const cell=document.createElement('td');cell.textContent=String(value);row.appendChild(cell)});const cell=document.createElement('td');cell.className='review-actions';const detail=document.createElement('button');detail.className='detail-button';detail.textContent='查看详情';detail.onclick=()=>loadPopoDetail(item.id);cell.appendChild(detail);if(['failed','partial'].includes(item.status)){const resume=document.createElement('button');resume.className='resume-button';resume.textContent='继续发送';resume.onclick=()=>resumePopo(item.id,resume);cell.appendChild(resume)}row.appendChild(cell);body.appendChild(row)})}
async function loadPopo(){if(!token)return;try{const [messages,capability]=await Promise.all([request('/api/admin/popo/messages'),request('/api/admin/popo/capabilities')]);popoRows(messages.items);text('popoCapability',capability.available?'管理可用':'管理降级')}catch(error){text('popoActionMessage',error.message)}}
async function loadPopoDetail(id){text('popoDetailSummary','正在加载…');try{const data=await request('/api/admin/popo/messages/'+encodeURIComponent(id));text('popoDetailSummary',(popoStatus[data.status]||data.status)+'｜分段 '+data.sentChunkCount+'/'+data.chunkCount+'｜尝试 '+data.attempts);messageContent('popoDetailContent',data.message);const list=byId('popoChunks');list.replaceChildren();data.chunks.forEach(chunk=>{const item=document.createElement('section');item.className='chunk-item';const header=document.createElement('header');const title=document.createElement('b');title.textContent='第 '+chunk.position+'/'+data.chunkCount+' 段｜'+(popoStatus[chunk.status]||chunk.status);const meta=document.createElement('span');meta.className='chunk-meta';meta.textContent='尝试 '+chunk.attempts+'｜msgId '+(chunk.msgId||'尚未生成');header.append(title,meta);const content=document.createElement('pre');messageContentNode(content,chunk.content);item.append(header,content);if(chunk.error){const error=document.createElement('div');error.className='warn';error.textContent=chunk.error;item.appendChild(error)}list.appendChild(item)})}catch(error){text('popoDetailSummary','加载失败');text('popoDetailContent',error.message)}}
function messageContentNode(target,value){target.replaceChildren();const holder=document.createElement('span');target.appendChild(holder);const id='temporaryMessageTarget';holder.id=id;messageContent(id,value);holder.removeAttribute('id')}
async function resumePopo(id,button){if(!confirm('确认从失败分段继续发送该 POPO 消息？'))return;button.disabled=true;text('popoActionMessage','正在从失败分段继续发送…');try{const data=await request('/api/admin/popo/messages/'+encodeURIComponent(id)+'/resume',{method:'POST',body:JSON.stringify({confirmation:'确认从失败分段继续发送'})});text('popoActionMessage',data.message);await loadPopo();await loadPopoDetail(id)}catch(error){text('popoActionMessage',error.message)}finally{button.disabled=false}}
function renderPreview(data){previewId=data.previewId||'';if(previewId)sessionStorage.setItem('latestPreviewId',previewId);text('previewSummary','巡检工单 '+data.scanned+' 个，发现 '+data.violations.length+' 项待完善内容');messageContent('previewContent',data.message||'本次巡检未发现需要发送的问题。');byId('acceptanceSend').disabled=!previewId}
async function action(path,body,buttonId,messageId='actionMessage'){const button=byId(buttonId);const original=button.textContent;button.disabled=true;button.textContent='处理中…';text(messageId,path.includes('preview')?'正在查询易协作工单，请稍候…':'正在提交请求…');try{const data=await request(path,{method:'POST',body:body?JSON.stringify(body):undefined});const violations=Array.isArray(data.violations)?data.violations:[];const summary=data.message||(data.previewId?'预览已生成：巡检工单 '+data.scanned+' 个，发现 '+violations.length+' 项待完善内容':typeof data.scanned==='number'?'巡检工单 '+data.scanned+' 个，发现 '+violations.length+' 项待完善内容':'操作已完成');text(messageId,data.previewId?'复核预览已生成，请检查下方内容。':summary);if(path.includes('preview'))renderPreview({...data,violations});load().catch(error=>text('globalMessage',error.message))}catch(error){text(messageId,error.message)}finally{button.disabled=buttonId==='acceptanceSend'?!previewId:false;button.textContent=original}}
const issueLabels=[['projectName','项目'],['id','#ID'],['subject','主题'],['assigneeName','指派给'],['statusName','状态'],['gameProduct','游戏产品'],['deliveryChannel','投放渠道'],['returnDeliveryChannel','回流投放渠道'],['aiDeliveryChannel','AI运营投放渠道'],['artCategory','美术需求分类'],['aiPipelineTime','AI管线耗时'],['totalHours','总工时'],['designQuantity','设计数量'],['expectedDeliveryDate','期望交付时间'],['startDate','开始日期'],['dueDate','完成日期'],['createdOn','创建时间'],['updatedOn','更新时间'],['closedOn','关闭时间']];
function appendText(row,value){const cell=document.createElement('td');cell.textContent=String(value??'');row.appendChild(cell)}
function showIssueDetail(item){text('issueDetailSummary','#'+item.id+' '+item.subject);const list=byId('issueDetailFields');list.replaceChildren();issueLabels.forEach(([key,label])=>{const term=document.createElement('dt');term.textContent=label;const desc=document.createElement('dd');if(key==='id'){const link=document.createElement('a');link.href=item.url;link.target='_blank';link.rel='noopener noreferrer';link.textContent='#'+item.id;desc.appendChild(link)}else desc.textContent=String(item[key]??'');list.append(term,desc)});list.scrollIntoView({behavior:'smooth',block:'nearest'})}
function issueRows(items){const body=byId('issueRows');body.replaceChildren();if(!items.length){const row=document.createElement('tr');const cell=document.createElement('td');cell.colSpan=10;cell.className='empty';cell.textContent='暂无入库工单';row.appendChild(cell);body.appendChild(row);return}items.forEach(item=>{const row=document.createElement('tr');row.className='issue-row';appendText(row,item.projectName);const idCell=document.createElement('td');const link=document.createElement('a');link.href=item.url;link.target='_blank';link.rel='noopener noreferrer';link.textContent='#'+item.id;link.onclick=event=>event.stopPropagation();idCell.appendChild(link);row.appendChild(idCell);[item.subject,item.assigneeName,item.statusName,item.gameProduct,item.totalHours,item.expectedDeliveryDate,item.updatedOn].forEach(value=>appendText(row,value));const cell=document.createElement('td');cell.className='review-actions';const button=document.createElement('button');button.type='button';button.className='detail-button';button.textContent='查看详情';button.onclick=event=>{event.stopPropagation();showIssueDetail(item)};cell.appendChild(button);row.onclick=()=>showIssueDetail(item);row.appendChild(cell);body.appendChild(row)})}
async function loadIssues(){if(!token)return;try{const data=await request('/api/admin/issues');issueRows(data.items);text('issueCount',data.total+' 条');text('issueActionMessage','')}catch(error){text('issueActionMessage',error.message)}}
document.querySelectorAll('[data-page]').forEach(button=>button.onclick=()=>{document.querySelectorAll('[data-page],.page').forEach(node=>node.classList.remove('active'));button.classList.add('active');byId(button.dataset.page).classList.add('active');if(button.dataset.page==='popo')loadPopo();if(button.dataset.page==='issues')loadIssues()});
byId('saveToken').onclick=()=>{const value=byId('adminToken').value.trim();if(!value){text('globalMessage','管理令牌不能为空');return}token=value;sessionStorage.setItem('workorderAdminToken',token);tokenView();text('globalMessage','管理令牌已保存到当前会话');load()};byId('clearToken').onclick=()=>{sessionStorage.removeItem('workorderAdminToken');token='';tokenView();text('globalMessage','管理令牌已清除')};
byId('saveSettings').onclick=()=>action('/api/admin/settings',{scheduleEnabled:byId('scheduleEnabled').checked,automaticSendEnabled:byId('automaticSendEnabled').checked,webhookProcessingEnabled:byId('webhookProcessingEnabled').checked},'saveSettings','globalMessage');byId('todayPreview').onclick=()=>action('/api/admin/preview-today',undefined,'todayPreview','quickActionMessage');byId('testSend').onclick=()=>action('/api/admin/test-notification',undefined,'testSend','quickActionMessage');byId('acceptancePreview').onclick=()=>action('/api/admin/acceptance-preview',{startDate:byId('startDate').value,endDate:byId('endDate').value},'acceptancePreview');byId('acceptanceSend').onclick=()=>action('/api/admin/acceptance-send',{previewId,confirmation:'确认发送正式巡检结果'},'acceptanceSend');
const today=new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Shanghai'});byId('startDate').value=today;byId('endDate').value=today;byId('acceptanceSend').disabled=!previewId;tokenView();load();`
}
