/** 返回不依赖构建产物的控制面浏览器脚本。 */
export function adminScript(): string {
  return `
const byId=id=>document.getElementById(id);
const text=(id,value)=>{const node=byId(id);if(node)node.textContent=String(value??'')};
const today=new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Shanghai'});
const base=location.pathname.replace(/[/]$/,'');
let previewId='';let statsData=null;
const request=async(path,options={})=>{const headers={...(options.body?{'content-type':'application/json'}:{}),...(options.headers||{})};const response=await fetch(base+path,{...options,headers});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'请求失败');return data};
function setMessage(id,value,isError=false){const node=byId(id);if(!node)return;node.className=isError?'message error':'message';node.textContent=value||''}
function fmtTime(value){if(!value)return'';const date=new Date(value);if(Number.isNaN(date.getTime()))return String(value);const pad=number=>String(number).padStart(2,'0');return date.getFullYear()+'-'+pad(date.getMonth()+1)+'-'+pad(date.getDate())+' '+pad(date.getHours())+':'+pad(date.getMinutes())}
function mk(value,className,title){return{text:value,className,title}}
function mkPill(value,kind){return{pill:{text:value,kind}}}
function addCell(row,value){const cell=document.createElement('td');const spec=(value&&typeof value==='object'&&!Array.isArray(value))?value:{text:value};if(spec.pill){const span=document.createElement('span');span.className='pill '+(spec.pill.kind||'');span.textContent=String(spec.pill.text??'');cell.appendChild(span)}else cell.textContent=String(spec.text??'');if(spec.className)cell.className=spec.className;if(spec.title)cell.title=String(spec.title);row.appendChild(cell)}
function emptyRow(body,columns,label){body.replaceChildren();const row=document.createElement('tr');const cell=document.createElement('td');cell.colSpan=columns;cell.className='empty';cell.textContent=label;row.appendChild(cell);body.appendChild(row)}
function boolLabel(value){return value?'已启用':'未启用'}
const webhookKind={pending:'info',processing:'info',completed:'ok',failed:'err','dead-letter':'err'};
function configure(id,value){text(id,value?'已配置':'未配置');byId(id).className=value?'ok':'warn'}
function renderStatus(data){byId('health').className=data.healthy?'status':'status warn';text('health',data.healthy?'运行正常':'服务异常');text('schedule',boolLabel(data.settings.scheduleEnabled));text('autoSend',boolLabel(data.settings.automaticSendEnabled));text('webhookProcessing',boolLabel(data.settings.webhookProcessingEnabled));text('reviewModel',data.review.model);byId('scheduleEnabled').checked=data.settings.scheduleEnabled;byId('automaticSendEnabled').checked=data.settings.automaticSendEnabled;byId('webhookProcessingEnabled').checked=data.settings.webhookProcessingEnabled;configure('gcpConfigured',data.configured.gcpUserKey);configure('popoConfigured',data.configured.popoWebhook);configure('webhookConfigured',data.configured.webhookEntry);text('projectConfig','项目映射：'+Object.entries(data.projects).map(([name,id])=>name+' '+id).join('；')+'。美术完成状态 ID：'+data.completedStatusId);simpleRows('runs',data.runs,6,item=>[mk(fmtTime(item.createdAt)),item.type,item.startDate+' 至 '+item.endDate,mk(item.scanned,'num'),mk(item.violationCount,'num'),mkPill(item.status,item.status==='completed'?'ok':'info')],'暂无巡检记录');simpleRows('events',data.webhooks,7,item=>[mk(fmtTime(item.createdAt)),mk(item.traceId,'mono truncate',item.traceId),mk('#'+item.issueId),mk(item.projectId,'num'),mkPill(item.status,webhookKind[item.status]||''),mk(item.attempts,'num'),mk(item.error||'','truncate',item.error||'')],'暂无 Webhook 事件');renderPreviews(data.previews);renderWebhookRequests(data)}
const requestOutcome={accepted:'已接收',duplicate:'重复忽略',ignored:'已忽略',invalid:'无效请求'};
const requestKind={accepted:'ok',duplicate:'info',ignored:'warn',invalid:'err'};
function renderWebhookRequests(data){const ingress=data.ingress||{};text('ingressInfo',ingress.enabled?'　独立入口：'+ingress.host+':'+ingress.port:'　独立入口：未启用');simpleRows('webhookRequests',data.webhookRequests||[],8,item=>[mk(fmtTime(item.at)),mk(item.source==='ingress'?'独立入口':'宿主入口'),mkPill(requestOutcome[item.outcome]||item.outcome,requestKind[item.outcome]||''),mk(item.reason,'truncate',item.reason),mk(item.module+' / '+item.event,'mono'),mk(item.issueId===undefined?'':'#'+item.issueId),mk(item.projectId===undefined?'':item.projectId,'num'),mk(item.bodyPreview,'mono truncate',item.bodyPreview)],'尚未收到任何回调')}
function simpleRows(id,items,columns,values,empty){const body=byId(id);if(!items.length){emptyRow(body,columns,empty);return}body.replaceChildren();items.forEach(item=>{const row=document.createElement('tr');values(item).forEach(value=>addCell(row,value));body.appendChild(row)})}
const vivoStatusLabel={ok:'正常',failed:'失败',unknown:'未知'};
let vivoPoll;
function fillSelect(id,values,placeholder){const select=byId(id);const current=select.value;select.replaceChildren();const blank=document.createElement('option');blank.value='';blank.textContent=placeholder;select.appendChild(blank);values.forEach(value=>{const option=document.createElement('option');option.value=value;option.textContent=value;select.appendChild(option)});if(values.includes(current))select.value=current}
function renderVivoCases(items){const body=byId('vivoRows');if(!items.length){emptyRow(body,10,'暂无命中案例');return}body.replaceChildren();items.forEach(item=>{const row=document.createElement('tr');const trend=item.isNew?mkPill('新','ok'):item.delta===undefined?mk('—','num'):mk((item.delta>0?'+':'')+item.delta+'%','num');[item.game,mk(item.position),item.category||item.tab,mk(item.name,'truncate',item.name),mk(item.ctrText,'num'),trend,mk(item.rank||'','num'),item.caseDate,mk(item.runId,'mono')].forEach(value=>addCell(row,value));const action=document.createElement('td');action.className='review-actions';const shot=document.createElement('button');shot.className='detail-button';shot.textContent='查看截图';shot.onclick=()=>showVivoShot(item);action.appendChild(shot);row.appendChild(action);body.appendChild(row)})}
function showVivoShot(item){text('vivoShotSummary',item.runId+'｜'+item.game+'｜'+item.position+'｜CTR '+item.ctrText);const pane=byId('vivoShot');pane.replaceChildren();if(!item.screenshot){pane.textContent='该案例未保存截图。';return}const image=document.createElement('img');image.src=base+'/api/admin/vivo/shot?runId='+encodeURIComponent(item.runId)+'&file='+encodeURIComponent(item.screenshot);image.alt=item.game+' '+item.position+' 案例截图';image.onerror=()=>{pane.textContent='截图文件不存在或已被清理。'};pane.appendChild(image);pane.scrollIntoView({behavior:'smooth',block:'nearest'})}
function renderVivoState(state){text('vivoCollectSummary',state.running?('采集中：'+(state.targets||[]).join('、')):(state.finishedAt?('上次结束 '+fmtTime(state.finishedAt)+'（退出码 '+(state.exitCode===undefined?'未知':state.exitCode)+'）'):'未运行'));text('vivoLog',(state.log||[]).join('\\n')||'尚未运行采集。');byId('vivoCollect').disabled=!!state.running;byId('vivoStop').disabled=!state.running;if(state.running){vivoPoll=setTimeout(async()=>{try{const next=await request('/api/admin/vivo/collect');renderVivoState(next);if(!next.running)await loadVivo()}catch{}},2500)}}
function renderVivo(data){const summary=byId('vivoSummary');summary.replaceChildren();const stats=data.summary||{};summary.append(statCard('采集轮次',stats.runs||0),statCard('案例条数',stats.cases||0),statCard('平均 CTR',(stats.averageCtr||0)+'%'),statCard('最近采集',stats.latest?fmtTime(stats.latest):'—'));text('vivoStatus',data.configured?'已连接':'未配置项目目录');byId('vivoStatus').className=data.configured?'status':'status warn';if(!byId('vivoTargets').value)byId('vivoTargets').value=(data.targets||[]).join('，');fillSelect('vivoGame',(data.facets||{}).games||[],'全部游戏');fillSelect('vivoPosition',(data.facets||{}).positions||[],'全部资源位');renderVivoCases(data.cases||[]);simpleRows('vivoRuns',data.runs||[],7,item=>[mk(item.id,'mono'),mk(fmtTime(item.collectedAt)),(item.targets||[]).join('、'),mk(item.caseCount,'num'),mk(item.scannedCount,'num'),mk(item.failedCount,'num'),mkPill(vivoStatusLabel[item.status]||item.status,item.status==='ok'?'ok':item.status==='failed'?'err':'')],'暂无采集轮次');renderVivoState(data.state||{running:false,log:[]})}
async function loadVivo(){const game=byId('vivoGame').value;const position=byId('vivoPosition').value;const query=[game?'game='+encodeURIComponent(game):'',position?'position='+encodeURIComponent(position):''].filter(Boolean).join('&');try{renderVivo(await request('/api/admin/vivo'+(query?'?'+query:'')))}catch(error){setMessage('vivoMessage',error.message,true)}}
async function startVivoCollect(){const targets=byId('vivoTargets').value.split(/[,，\s]+/).map(item=>item.trim()).filter(Boolean);const button=byId('vivoCollect');button.disabled=true;setMessage('vivoMessage','正在启动采集…');try{const data=await request('/api/admin/vivo/collect',{method:'POST',body:JSON.stringify({targets})});text('vivoMessage',data.message);renderVivoState(data.state)}catch(error){setMessage('vivoMessage',error.message,true);button.disabled=false}}
async function syncVivo(){const button=byId('vivoSync');button.disabled=true;try{renderVivo(await request('/api/admin/vivo/sync',{method:'POST'}));text('vivoMessage','已同步采集历史')}catch(error){setMessage('vivoMessage',error.message,true)}finally{button.disabled=false}}
async function stopVivoCollect(){const button=byId('vivoStop');button.disabled=true;try{const data=await request('/api/admin/vivo/collect/stop',{method:'POST'});text('vivoMessage',data.message);renderVivoState(data.state)}catch(error){setMessage('vivoMessage',error.message,true)}}
async function notifyVivo(){if(!confirm('确认把最新一轮 vivo 命中案例推送到 POPO 群？'))return;const button=byId('vivoNotify');button.disabled=true;try{const data=await request('/api/admin/vivo/notify',{method:'POST',body:JSON.stringify({})});text('vivoMessage',data.message)}catch(error){setMessage('vivoMessage',error.message,true)}finally{button.disabled=false}}
async function loadStatus(){try{renderStatus(await request('/api/admin/status'));setMessage('globalMessage','')}catch(error){setMessage('globalMessage',error.message,true)}}
const issueLabels=[['projectName','项目'],['id','#ID'],['subject','主题'],['submitterName','提单人'],['assigneeName','指派给'],['statusName','状态'],['gameProduct','游戏产品'],['deliveryChannel','投放渠道'],['returnDeliveryChannel','回流投放渠道'],['aiDeliveryChannel','AI运营投放渠道'],['artCategory','美术需求分类'],['aiPipelineTime','AI管线耗时'],['totalHours','总工时'],['designQuantity','设计数量'],['expectedDeliveryDate','期望交付时间'],['startDate','开始日期'],['dueDate','完成日期'],['createdOn','创建时间'],['updatedOn','更新时间'],['closedOn','关闭时间']];
function showIssue(item){text('issueDetailSummary','#'+item.id+' '+item.subject);const list=byId('issueDetailFields');list.replaceChildren();issueLabels.forEach(([key,label])=>{const term=document.createElement('dt');term.textContent=label;const desc=document.createElement('dd');if(key==='id'){const link=document.createElement('a');link.href=item.url;link.target='_blank';link.rel='noopener noreferrer';link.textContent='#'+item.id;desc.appendChild(link)}else desc.textContent=String(item[key]??'');list.append(term,desc)});list.scrollIntoView({behavior:'smooth',block:'nearest'})}
function renderIssues(items){const body=byId('issueRows');if(!items.length){emptyRow(body,11,'暂无入库工单');return}body.replaceChildren();items.forEach(item=>{const row=document.createElement('tr');row.className='row-action';addCell(row,item.projectName);const idCell=document.createElement('td');idCell.className='mono';const link=document.createElement('a');link.href=item.url;link.target='_blank';link.rel='noopener noreferrer';link.textContent='#'+item.id;link.onclick=event=>event.stopPropagation();idCell.appendChild(link);row.appendChild(idCell);[mk(item.subject,'truncate',item.subject),item.submitterName||'未识别',item.assigneeName,item.statusName,item.gameProduct,mk(item.totalHours,'num'),item.expectedDeliveryDate,mk(fmtTime(item.updatedOn))].forEach(value=>addCell(row,value));const action=document.createElement('td');const detail=document.createElement('button');detail.className='detail-button';detail.textContent='查看详情';detail.onclick=event=>{event.stopPropagation();showIssue(item)};action.appendChild(detail);row.appendChild(action);row.onclick=()=>showIssue(item);body.appendChild(row)})}
async function loadIssues(){try{const data=await request('/api/admin/issues');renderIssues(data.items);text('issueCount',data.total+' 条');setMessage('issueActionMessage','')}catch(error){setMessage('issueActionMessage',error.message,true)}}
async function syncIssues(){const startDate=byId('issuesStartDate').value;const endDate=byId('issuesEndDate').value;if(!startDate||!endDate){setMessage('issueSyncMessage','请选择完整日期范围',true);return}const button=byId('issuesSync');button.disabled=true;text('issueSyncMessage','正在查询易协作工单，请稍候…');try{const data=await request('/api/admin/issues/sync',{method:'POST',body:JSON.stringify({startDate,endDate})});renderIssues(data.items);text('issueSyncMessage',data.message);await loadIssues()}catch(error){setMessage('issueSyncMessage',error.message,true)}finally{button.disabled=false}}
const reviewModelStatus={completed:'已完成',failed:'失败',skipped:'已跳过'};const reviewNotificationStatus={'not-required':'无需提醒',disabled:'已关闭',blocked:'被自动发送开关阻止',sent:'已发送','in-progress':'发送中',failed:'发送失败'};
const reviewModelKind={completed:'ok',failed:'err',skipped:'warn'};const reviewNotifyKind={'not-required':'',disabled:'',blocked:'warn',sent:'ok','in-progress':'info',failed:'err'};
function renderIssueReviews(items){const body=byId('issueReviewRows');text('reviewCount',items.length+' 条');if(!items.length){emptyRow(body,8,'暂无填写核验记录');return}body.replaceChildren();items.forEach(item=>{const row=document.createElement('tr');row.className='row-action';[mk(fmtTime(item.createdAt)),mk('#'+item.issueId),item.submitterName||'未识别',item.triggerType,mk(item.violations.length,'num'),mkPill(reviewModelStatus[item.modelStatus]||item.modelStatus,reviewModelKind[item.modelStatus]||''),mkPill(reviewNotificationStatus[item.notificationStatus]||item.notificationStatus,reviewNotifyKind[item.notificationStatus]||'')].forEach(value=>addCell(row,value));const action=document.createElement('td');const detail=document.createElement('button');detail.className='detail-button';detail.textContent='查看详情';detail.onclick=event=>{event.stopPropagation();showIssueReview(item.id)};action.appendChild(detail);row.appendChild(action);row.onclick=()=>showIssueReview(item.id);body.appendChild(row)})}
async function loadIssueReviews(){try{renderIssueReviews((await request('/api/admin/issue-reviews')).items)}catch(error){setMessage('reviewActionMessage',error.message,true)}}
async function showIssueReview(id){text('issueReviewSummary','正在加载…');text('issueReviewContent','');try{const item=await request('/api/admin/issue-reviews/'+encodeURIComponent(id));const lines=['工单：#'+item.issueId+'｜'+item.projectName,'提单人：'+(item.submitterName||'未识别'),'规则核验：'+(item.violations.length?item.violations.map(value=>value.message).join('；'):'未发现规则缺项'),'模型状态：'+(reviewModelStatus[item.modelStatus]||item.modelStatus),'模型结论：'+item.modelOutput,'POPO 回执：'+(reviewNotificationStatus[item.notificationStatus]||item.notificationStatus)];if(item.notificationTaskId)lines.push('消息任务：'+item.notificationTaskId);if(item.notificationError)lines.push('消息错误：'+item.notificationError);text('issueReviewSummary',item.createdAt+'｜'+item.triggerType);text('issueReviewContent',lines.join('\\n\\n'))}catch(error){text('issueReviewSummary','加载失败');text('issueReviewContent',error.message)}}
async function reviewIssue(){const issueId=Number(byId('reviewIssueId').value);if(!Number.isInteger(issueId)||issueId<=0){setMessage('reviewActionMessage','请输入有效的已入库工单 ID',true);return}const button=byId('reviewIssue');button.disabled=true;text('reviewActionMessage','正在执行规则与模型填写核验…');try{const data=await request('/api/admin/issues/'+issueId+'/review',{method:'POST'});text('reviewActionMessage',data.message);await Promise.all([loadIssueReviews(),loadStatus()]);if(data.reviewId)await showIssueReview(data.reviewId)}catch(error){setMessage('reviewActionMessage',error.message,true)}finally{button.disabled=false}}
function renderPreviews(items){const body=byId('previewRows');if(!items.length){emptyRow(body,5,'暂无巡检预览');return}body.replaceChildren();items.forEach(item=>{const row=document.createElement('tr');[mk(fmtTime(item.createdAt)),item.startDate+' 至 '+item.endDate,mkPill(item.status==='sent'?'已发送':'待发送',item.status==='sent'?'ok':'info'),mk(fmtTime(item.expiresAt))].forEach(value=>addCell(row,value));const action=document.createElement('td');const detail=document.createElement('button');detail.className='detail-button';detail.textContent='查看详情';detail.onclick=()=>showPreview(item.id);const resend=document.createElement('button');resend.className='resend-button';resend.textContent='再次发送';resend.onclick=()=>resendPreview(item.id,resend);action.append(detail,resend);row.appendChild(action);body.appendChild(row)})}
async function showPreview(id){text('previewDetailSummary','正在加载…');text('previewDetailContent','');try{const data=await request('/api/admin/previews/'+encodeURIComponent(id));text('previewDetailSummary',data.startDate+' 至 '+data.endDate+'｜工单 '+data.scanned+' 个｜待完善项 '+data.violationCount+' 项');text('previewDetailContent',data.message||'本次巡检未发现待发送内容。')}catch(error){text('previewDetailSummary','加载失败');text('previewDetailContent',error.message)}}
async function resendPreview(id,button){if(!confirm('确认再次发送该巡检预览至 POPO？'))return;button.disabled=true;setMessage('previewActionMessage','正在再次发送…');try{const data=await request('/api/admin/previews/'+encodeURIComponent(id)+'/resend',{method:'POST',body:JSON.stringify({confirmation:'确认再次发送复核结果'})});text('previewActionMessage',data.message)}catch(error){setMessage('previewActionMessage',error.message,true)}finally{button.disabled=false}}
const popoStatus={pending:'待发送',sending:'发送中',partial:'部分成功',sent:'已发送',failed:'发送失败','dead-letter':'停止重试'};
const popoKind={pending:'info',sending:'info',partial:'warn',sent:'ok',failed:'err','dead-letter':'err'};
function renderPopo(items){const body=byId('popoRows');if(!items.length){emptyRow(body,7,'暂无消息记录');return}body.replaceChildren();items.forEach(item=>{const row=document.createElement('tr');[mk(fmtTime(item.createdAt)),item.sourceType,mkPill(popoStatus[item.status]||item.status,popoKind[item.status]||''),mk(item.sentChunkCount+' / '+item.chunkCount,'num'),mk(item.attempts,'num'),mk(item.error||'','truncate',item.error||'')].forEach(value=>addCell(row,value));const action=document.createElement('td');action.className='review-actions';const detail=document.createElement('button');detail.className='detail-button';detail.textContent='查看详情';detail.onclick=()=>showPopo(item.id);action.appendChild(detail);if(['failed','partial'].includes(item.status)){const resume=document.createElement('button');resume.className='resume-button';resume.textContent='继续发送';resume.onclick=()=>resumePopo(item.id,resume);action.appendChild(resume)}row.appendChild(action);body.appendChild(row)})}
async function loadPopo(){try{const result=await Promise.all([request('/api/admin/popo/messages'),request('/api/admin/popo/capabilities')]);renderPopo(result[0].items);text('popoCapability',result[1].available?'管理可用':'管理降级')}catch(error){setMessage('popoActionMessage',error.message,true)}}
async function showPopo(id){text('popoDetailSummary','正在加载…');try{const data=await request('/api/admin/popo/messages/'+encodeURIComponent(id));text('popoDetailSummary',(popoStatus[data.status]||data.status)+'｜分段 '+data.sentChunkCount+'/'+data.chunkCount+'｜尝试 '+data.attempts);text('popoDetailContent',data.message);const list=byId('popoChunks');list.replaceChildren();data.chunks.forEach(chunk=>{const item=document.createElement('section');item.className='chunk-item';const header=document.createElement('header');const title=document.createElement('b');title.textContent='第 '+chunk.position+'/'+data.chunkCount+' 段｜'+(popoStatus[chunk.status]||chunk.status);const meta=document.createElement('span');meta.className='chunk-meta';meta.textContent='尝试 '+chunk.attempts+'｜msgId '+(chunk.msgId||'尚未生成');header.append(title,meta);const content=document.createElement('pre');content.textContent=chunk.content;item.append(header,content);if(chunk.error){const error=document.createElement('div');error.className='error';error.textContent=chunk.error;item.appendChild(error)}list.appendChild(item)})}catch(error){text('popoDetailSummary','加载失败');text('popoDetailContent',error.message)}}
async function resumePopo(id,button){if(!confirm('确认从失败分段继续发送该 POPO 消息？'))return;button.disabled=true;setMessage('popoActionMessage','正在继续发送…');try{const data=await request('/api/admin/popo/messages/'+encodeURIComponent(id)+'/resume',{method:'POST',body:JSON.stringify({confirmation:'确认从失败分段继续发送'})});text('popoActionMessage',data.message);await Promise.all([loadPopo(),showPopo(id)])}catch(error){setMessage('popoActionMessage',error.message,true)}finally{button.disabled=false}}
function statCard(label,value){const card=document.createElement('article');card.className='card';const name=document.createElement('span');name.className='label';name.textContent=label;const metric=document.createElement('div');metric.className='metric';metric.textContent=String(value);card.append(name,metric);return card}
function table(headers,rows){const value=document.createElement('table');const head=document.createElement('thead');const headRow=document.createElement('tr');headers.forEach(item=>{const cell=document.createElement('th');const spec=(item&&typeof item==='object')?item:{text:item};cell.textContent=String(spec.text??'');if(spec.className)cell.className=spec.className;headRow.appendChild(cell)});head.appendChild(headRow);const body=document.createElement('tbody');rows.forEach(row=>{const element=document.createElement('tr');row.forEach(item=>addCell(element,item));body.appendChild(element)});value.append(head,body);return value}
function statBlock(title,headers,rows){const card=document.createElement('article');card.className='card wide table-scroll';const heading=document.createElement('h2');heading.textContent=title;card.append(heading,table(headers,rows));return card}
function renderStats(data){statsData=data;const result=byId('statsResult');result.replaceChildren();const summary=document.createElement('div');summary.className='grid';summary.append(statCard('设计数量总计',data.total.quantity),statCard('工单条数',data.issueCount),statCard('AI 管线占比',data.total.aiRatio+'%'),statCard('人工占比',data.total.manualRatio+'%'));result.appendChild(summary);result.appendChild(statBlock('分类统计',['分类',mk('设计数量','num'),mk('AI 数量','num'),mk('AI 占比','num'),mk('人工占比','num')],data.categories.map(item=>[item.category,mk(item.quantity,'num'),mk(item.aiQuantity,'num'),mk(item.aiRatio+'%','num'),mk(item.manualRatio+'%','num')])));result.appendChild(statBlock('各游戏产品设计数量合计',['游戏产品',mk('设计数量','num')],data.games.map(item=>[item.name,mk(item.quantity,'num')])));result.appendChild(statBlock('各指派给设计数量合计',['指派给',mk('设计数量','num'),mk('AI 占比','num')],data.assignees.map(item=>[item.name,mk(item.stat.quantity,'num'),mk(item.stat.aiRatio+'%','num')])));text('statsStatus',data.startDate&&data.endDate?data.startDate+' 至 '+data.endDate:'全部数据');byId('statsExport').disabled=false}
async function loadStats(){const startDate=byId('statsStartDate').value;const endDate=byId('statsEndDate').value;const query=[startDate?'startDate='+encodeURIComponent(startDate):'',endDate?'endDate='+encodeURIComponent(endDate):''].filter(Boolean).join('&');try{renderStats(await request('/api/admin/stats'+(query?'?'+query:'')));text('statsMessage','统计完成')}catch(error){setMessage('statsMessage',error.message,true)}}
function exportStats(){if(!statsData)return;const lines=['工单统计','设计数量总计：'+statsData.total.quantity,'AI 管线占比：'+statsData.total.aiRatio+'%','人工占比：'+statsData.total.manualRatio+'%','','分类统计'];statsData.categories.forEach(item=>lines.push(item.category+'：'+item.quantity));lines.push('','各游戏产品设计数量合计');statsData.games.forEach(item=>lines.push(item.name+'：'+item.quantity));const blob=new Blob([lines.join('\\r\\n')],{type:'text/plain;charset=utf-8'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=(statsData.startDate&&statsData.endDate?statsData.startDate+'-'+statsData.endDate:'工单')+'统计.txt';link.click();URL.revokeObjectURL(link.href)}
async function inspection(path,body,buttonId,messageId){const button=byId(buttonId);button.disabled=true;setMessage(messageId,path.includes('preview')?'正在查询易协作工单，请稍候…':'正在提交请求…');try{const data=await request(path,{method:'POST',...(body?{body:JSON.stringify(body)}:{})});if(data.previewId){previewId=data.previewId;text('inspectionPreviewSummary','巡检工单 '+data.scanned+' 个，待完善项 '+data.violations.length+' 项');text('inspectionPreviewContent',data.message||'本次巡检未发现待发送内容。');byId('acceptanceSend').disabled=false}text(messageId,data.message||'操作已完成');await loadStatus()}catch(error){setMessage(messageId,error.message,true)}finally{button.disabled=buttonId==='acceptanceSend'?!previewId:false}}
async function loadReviewSettings(){try{const data=await request('/api/admin/review-settings');byId('reviewEnabled').checked=data.reviewEnabled;byId('reviewProvider').value=data.reviewProvider;byId('reviewModelInput').value=data.reviewModel;byId('reviewMaxTokens').value=data.reviewMaxTokens;byId('reviewKnowledgeBase').value=data.reviewKnowledgeBase;byId('reviewNotificationEnabled').checked=data.reviewNotificationEnabled}catch(error){setMessage('reviewSettingsMessage',error.message,true)}}
async function saveReviewSettings(){const button=byId('saveReviewSettings');button.disabled=true;setMessage('reviewSettingsMessage','正在保存审核配置…');const body={reviewEnabled:byId('reviewEnabled').checked,reviewProvider:byId('reviewProvider').value.trim(),reviewModel:byId('reviewModelInput').value.trim(),reviewMaxTokens:Number(byId('reviewMaxTokens').value),reviewKnowledgeBase:byId('reviewKnowledgeBase').value,reviewNotificationEnabled:byId('reviewNotificationEnabled').checked};try{const data=await request('/api/admin/review-settings',{method:'POST',body:JSON.stringify(body)});text('reviewSettingsMessage',data.message);setTimeout(()=>location.reload(),700)}catch(error){setMessage('reviewSettingsMessage',error.message,true);button.disabled=false}}
async function saveRuntime(){const button=byId('saveSettings');button.disabled=true;try{const data=await request('/api/admin/settings',{method:'POST',body:JSON.stringify({scheduleEnabled:byId('scheduleEnabled').checked,automaticSendEnabled:byId('automaticSendEnabled').checked,webhookProcessingEnabled:byId('webhookProcessingEnabled').checked})});text('globalMessage',data.message);await loadStatus()}catch(error){setMessage('globalMessage',error.message,true)}finally{button.disabled=false}}
function activate(page){document.querySelectorAll('[data-page],.page').forEach(item=>item.classList.remove('active'));document.querySelector('[data-page="'+page+'"]').classList.add('active');byId(page).classList.add('active');if(page==='issues')loadIssues();if(page==='validation')loadIssueReviews();if(page==='stats')loadStats();if(page==='vivo')loadVivo();if(page==='popo')loadPopo();if(page==='webhooks')loadStatus();if(page==='settings')loadReviewSettings()}
document.querySelectorAll('[data-page]').forEach(button=>button.onclick=()=>activate(button.dataset.page));
byId('issuesSync').onclick=syncIssues;byId('issuesReload').onclick=loadIssues;byId('vivoCollect').onclick=startVivoCollect;byId('vivoStop').onclick=stopVivoCollect;byId('vivoSync').onclick=syncVivo;byId('vivoNotify').onclick=notifyVivo;byId('vivoReload').onclick=loadVivo;byId('vivoGame').onchange=loadVivo;byId('vivoPosition').onchange=loadVivo;byId('reviewIssue').onclick=reviewIssue;byId('reviewReload').onclick=loadIssueReviews;byId('statsQuery').onclick=loadStats;byId('statsExport').onclick=exportStats;byId('saveSettings').onclick=saveRuntime;byId('saveReviewSettings').onclick=saveReviewSettings;byId('todayPreview').onclick=()=>inspection('/api/admin/preview-today',null,'todayPreview','quickActionMessage');byId('testSend').onclick=()=>inspection('/api/admin/test-notification',null,'testSend','quickActionMessage');byId('acceptancePreview').onclick=()=>inspection('/api/admin/acceptance-preview',{startDate:byId('startDate').value,endDate:byId('endDate').value},'acceptancePreview','actionMessage');byId('acceptanceSend').onclick=()=>inspection('/api/admin/acceptance-send',{previewId,confirmation:'确认发送正式巡检结果'},'acceptanceSend','actionMessage');
['issuesStartDate','issuesEndDate','statsStartDate','statsEndDate','startDate','endDate'].forEach(id=>byId(id).value=today);
function mountDesktopBar(){const api=window.__TAURI__;if(!api||!api.window||typeof api.window.getCurrentWindow!=='function')return;const bar=document.querySelector('[data-desktop-bar]');bar.hidden=false;document.body.classList.add('has-desktop-bar');const appWindow=api.window.getCurrentWindow();const actions={minimize:()=>appWindow.minimize(),maximize:()=>appWindow.toggleMaximize(),close:()=>appWindow.close()};Object.entries(actions).forEach(([name,run])=>{const button=bar.querySelector('[data-window="'+name+'"]');if(button)button.onclick=()=>{void run()}})}
mountDesktopBar();loadStatus();
`
}
