/** 返回不依赖构建产物的控制面浏览器脚本。 */
export function adminScript(): string {
  return `
const byId=id=>document.getElementById(id);
const text=(id,value)=>{const node=byId(id);if(node)node.textContent=String(value??'')};
const today=new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Shanghai'});
let token=sessionStorage.getItem('workorderAdminToken')||'';
let previewId='';let statsData=null;
const request=async(path,options={})=>{const headers={...(options.body?{'content-type':'application/json'}:{}),...(token?{authorization:'Bearer '+token}:{})};const response=await fetch(path,{...options,headers:{...headers,...(options.headers||{})}});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'请求失败');return data};
function tokenView(){byId('adminToken').value=token;text('tokenState',token?'已保存到当前会话':'未保存')}
function setMessage(id,value,isError=false){const node=byId(id);if(!node)return;node.className=isError?'message error':'message';node.textContent=value||''}
function addCell(row,value){const cell=document.createElement('td');cell.textContent=String(value??'');row.appendChild(cell)}
function emptyRow(body,columns,label){body.replaceChildren();const row=document.createElement('tr');const cell=document.createElement('td');cell.colSpan=columns;cell.className='empty';cell.textContent=label;row.appendChild(cell);body.appendChild(row)}
function boolLabel(value){return value?'已启用':'未启用'}
function configure(id,value){text(id,value?'已配置':'未配置');byId(id).className=value?'ok':'warn'}
function renderStatus(data){text('health',data.healthy?'运行正常':'服务异常');text('schedule',boolLabel(data.settings.scheduleEnabled));text('autoSend',boolLabel(data.settings.automaticSendEnabled));text('webhookProcessing',boolLabel(data.settings.webhookProcessingEnabled));text('reviewModel',data.review.model);byId('scheduleEnabled').checked=data.settings.scheduleEnabled;byId('automaticSendEnabled').checked=data.settings.automaticSendEnabled;byId('webhookProcessingEnabled').checked=data.settings.webhookProcessingEnabled;configure('gcpConfigured',data.configured.gcpUserKey);configure('popoConfigured',data.configured.popoWebhook);configure('webhookConfigured',data.configured.webhookEntry);configure('adminConfigured',data.configured.adminToken);text('projectConfig','项目映射：'+Object.entries(data.projects).map(([name,id])=>name+' '+id).join('；')+'。美术完成状态 ID：'+data.completedStatusId);simpleRows('runs',data.runs,6,item=>[item.createdAt,item.type,item.startDate+' 至 '+item.endDate,item.scanned,item.violationCount,item.status],'暂无巡检记录');simpleRows('events',data.webhooks,7,item=>[item.createdAt,item.traceId,item.issueId,item.projectId,item.status,item.attempts,item.error||''],'暂无 Webhook 事件');renderPreviews(data.previews)}
function simpleRows(id,items,columns,values,empty){const body=byId(id);if(!items.length){emptyRow(body,columns,empty);return}body.replaceChildren();items.forEach(item=>{const row=document.createElement('tr');values(item).forEach(value=>addCell(row,value));body.appendChild(row)})}
async function loadStatus(){if(!token)return;try{renderStatus(await request('/api/admin/status'));setMessage('globalMessage','')}catch(error){setMessage('globalMessage',error.message,true)}}
const issueLabels=[['projectName','项目'],['id','#ID'],['subject','主题'],['submitterName','提单人'],['assigneeName','指派给'],['statusName','状态'],['gameProduct','游戏产品'],['deliveryChannel','投放渠道'],['returnDeliveryChannel','回流投放渠道'],['aiDeliveryChannel','AI运营投放渠道'],['artCategory','美术需求分类'],['aiPipelineTime','AI管线耗时'],['totalHours','总工时'],['designQuantity','设计数量'],['expectedDeliveryDate','期望交付时间'],['startDate','开始日期'],['dueDate','完成日期'],['createdOn','创建时间'],['updatedOn','更新时间'],['closedOn','关闭时间']];
function showIssue(item){text('issueDetailSummary','#'+item.id+' '+item.subject);const list=byId('issueDetailFields');list.replaceChildren();issueLabels.forEach(([key,label])=>{const term=document.createElement('dt');term.textContent=label;const desc=document.createElement('dd');if(key==='id'){const link=document.createElement('a');link.href=item.url;link.target='_blank';link.rel='noopener noreferrer';link.textContent='#'+item.id;desc.appendChild(link)}else desc.textContent=String(item[key]??'');list.append(term,desc)});list.scrollIntoView({behavior:'smooth',block:'nearest'})}
function renderIssues(items){const body=byId('issueRows');if(!items.length){emptyRow(body,11,'暂无入库工单');return}body.replaceChildren();items.forEach(item=>{const row=document.createElement('tr');row.className='row-action';addCell(row,item.projectName);const idCell=document.createElement('td');const link=document.createElement('a');link.href=item.url;link.target='_blank';link.rel='noopener noreferrer';link.textContent='#'+item.id;link.onclick=event=>event.stopPropagation();idCell.appendChild(link);row.appendChild(idCell);[item.subject,item.submitterName||'未识别',item.assigneeName,item.statusName,item.gameProduct,item.totalHours,item.expectedDeliveryDate,item.updatedOn].forEach(value=>addCell(row,value));const action=document.createElement('td');const detail=document.createElement('button');detail.className='detail-button';detail.textContent='查看详情';detail.onclick=event=>{event.stopPropagation();showIssue(item)};action.appendChild(detail);row.appendChild(action);row.onclick=()=>showIssue(item);body.appendChild(row)})}
async function loadIssues(){if(!token)return;try{const data=await request('/api/admin/issues');renderIssues(data.items);text('issueCount',data.total+' 条');setMessage('issueActionMessage','')}catch(error){setMessage('issueActionMessage',error.message,true)}}
async function syncIssues(){const startDate=byId('issuesStartDate').value;const endDate=byId('issuesEndDate').value;if(!startDate||!endDate){setMessage('issueSyncMessage','请选择完整日期范围',true);return}const button=byId('issuesSync');button.disabled=true;text('issueSyncMessage','正在查询易协作工单，请稍候…');try{const data=await request('/api/admin/issues/sync',{method:'POST',body:JSON.stringify({startDate,endDate})});renderIssues(data.items);text('issueSyncMessage',data.message);await loadIssues()}catch(error){setMessage('issueSyncMessage',error.message,true)}finally{button.disabled=false}}
const reviewModelStatus={completed:'已完成',failed:'失败',skipped:'已跳过'};const reviewNotificationStatus={'not-required':'无需提醒',disabled:'已关闭',blocked:'被自动发送开关阻止',sent:'已发送','in-progress':'发送中',failed:'发送失败'};
function renderIssueReviews(items){const body=byId('issueReviewRows');text('reviewCount',items.length+' 条');if(!items.length){emptyRow(body,8,'暂无填写核验记录');return}body.replaceChildren();items.forEach(item=>{const row=document.createElement('tr');[item.createdAt,'#'+item.issueId,item.submitterName||'未识别',item.triggerType,item.violations.length,reviewModelStatus[item.modelStatus]||item.modelStatus,reviewNotificationStatus[item.notificationStatus]||item.notificationStatus].forEach(value=>addCell(row,value));const action=document.createElement('td');const detail=document.createElement('button');detail.className='detail-button';detail.textContent='查看详情';detail.onclick=()=>showIssueReview(item.id);action.appendChild(detail);row.appendChild(action);row.onclick=()=>showIssueReview(item.id);body.appendChild(row)})}
async function loadIssueReviews(){if(!token)return;try{renderIssueReviews((await request('/api/admin/issue-reviews')).items)}catch(error){setMessage('reviewActionMessage',error.message,true)}}
async function showIssueReview(id){text('issueReviewSummary','正在加载…');text('issueReviewContent','');try{const item=await request('/api/admin/issue-reviews/'+encodeURIComponent(id));const lines=['工单：#'+item.issueId+'｜'+item.projectName,'提单人：'+(item.submitterName||'未识别'),'规则核验：'+(item.violations.length?item.violations.map(value=>value.message).join('；'):'未发现规则缺项'),'模型状态：'+(reviewModelStatus[item.modelStatus]||item.modelStatus),'模型结论：'+item.modelOutput,'POPO 回执：'+(reviewNotificationStatus[item.notificationStatus]||item.notificationStatus)];if(item.notificationTaskId)lines.push('消息任务：'+item.notificationTaskId);if(item.notificationError)lines.push('消息错误：'+item.notificationError);text('issueReviewSummary',item.createdAt+'｜'+item.triggerType);text('issueReviewContent',lines.join('\\n\\n'))}catch(error){text('issueReviewSummary','加载失败');text('issueReviewContent',error.message)}}
async function reviewIssue(){const issueId=Number(byId('reviewIssueId').value);if(!Number.isInteger(issueId)||issueId<=0){setMessage('reviewActionMessage','请输入有效的已入库工单 ID',true);return}const button=byId('reviewIssue');button.disabled=true;text('reviewActionMessage','正在执行规则与模型填写核验…');try{const data=await request('/api/admin/issues/'+issueId+'/review',{method:'POST'});text('reviewActionMessage',data.message);await Promise.all([loadIssueReviews(),loadStatus()]);if(data.reviewId)await showIssueReview(data.reviewId)}catch(error){setMessage('reviewActionMessage',error.message,true)}finally{button.disabled=false}}
function renderPreviews(items){const body=byId('previewRows');if(!items.length){emptyRow(body,5,'暂无巡检预览');return}body.replaceChildren();items.forEach(item=>{const row=document.createElement('tr');[item.createdAt,item.startDate+' 至 '+item.endDate,item.status,item.expiresAt].forEach(value=>addCell(row,value));const action=document.createElement('td');const detail=document.createElement('button');detail.className='detail-button';detail.textContent='查看详情';detail.onclick=()=>showPreview(item.id);const resend=document.createElement('button');resend.className='resend-button';resend.textContent='再次发送';resend.onclick=()=>resendPreview(item.id,resend);action.append(detail,resend);row.appendChild(action);body.appendChild(row)})}
async function showPreview(id){text('previewDetailSummary','正在加载…');text('previewDetailContent','');try{const data=await request('/api/admin/previews/'+encodeURIComponent(id));text('previewDetailSummary',data.startDate+' 至 '+data.endDate+'｜工单 '+data.scanned+' 个｜待完善项 '+data.violationCount+' 项');text('previewDetailContent',data.message||'本次巡检未发现待发送内容。')}catch(error){text('previewDetailSummary','加载失败');text('previewDetailContent',error.message)}}
async function resendPreview(id,button){if(!confirm('确认再次发送该巡检预览至 POPO？'))return;button.disabled=true;setMessage('previewActionMessage','正在再次发送…');try{const data=await request('/api/admin/previews/'+encodeURIComponent(id)+'/resend',{method:'POST',body:JSON.stringify({confirmation:'确认再次发送复核结果'})});text('previewActionMessage',data.message)}catch(error){setMessage('previewActionMessage',error.message,true)}finally{button.disabled=false}}
const popoStatus={pending:'待发送',sending:'发送中',partial:'部分成功',sent:'已发送',failed:'发送失败','dead-letter':'停止重试'};
function renderPopo(items){const body=byId('popoRows');if(!items.length){emptyRow(body,7,'暂无消息记录');return}body.replaceChildren();items.forEach(item=>{const row=document.createElement('tr');[item.createdAt,item.sourceType,popoStatus[item.status]||item.status,item.sentChunkCount+'/'+item.chunkCount,item.attempts,item.error||''].forEach(value=>addCell(row,value));const action=document.createElement('td');const detail=document.createElement('button');detail.className='detail-button';detail.textContent='查看详情';detail.onclick=()=>showPopo(item.id);action.appendChild(detail);if(['failed','partial'].includes(item.status)){const resume=document.createElement('button');resume.className='resume-button';resume.textContent='继续发送';resume.onclick=()=>resumePopo(item.id,resume);action.appendChild(resume)}row.appendChild(action);body.appendChild(row)})}
async function loadPopo(){if(!token)return;try{const result=await Promise.all([request('/api/admin/popo/messages'),request('/api/admin/popo/capabilities')]);renderPopo(result[0].items);text('popoCapability',result[1].available?'管理可用':'管理降级')}catch(error){setMessage('popoActionMessage',error.message,true)}}
async function showPopo(id){text('popoDetailSummary','正在加载…');try{const data=await request('/api/admin/popo/messages/'+encodeURIComponent(id));text('popoDetailSummary',(popoStatus[data.status]||data.status)+'｜分段 '+data.sentChunkCount+'/'+data.chunkCount+'｜尝试 '+data.attempts);text('popoDetailContent',data.message);const list=byId('popoChunks');list.replaceChildren();data.chunks.forEach(chunk=>{const item=document.createElement('section');item.className='chunk-item';const header=document.createElement('header');const title=document.createElement('b');title.textContent='第 '+chunk.position+'/'+data.chunkCount+' 段｜'+(popoStatus[chunk.status]||chunk.status);const meta=document.createElement('span');meta.className='chunk-meta';meta.textContent='尝试 '+chunk.attempts+'｜msgId '+(chunk.msgId||'尚未生成');header.append(title,meta);const content=document.createElement('pre');content.textContent=chunk.content;item.append(header,content);if(chunk.error){const error=document.createElement('div');error.className='error';error.textContent=chunk.error;item.appendChild(error)}list.appendChild(item)})}catch(error){text('popoDetailSummary','加载失败');text('popoDetailContent',error.message)}}
async function resumePopo(id,button){if(!confirm('确认从失败分段继续发送该 POPO 消息？'))return;button.disabled=true;setMessage('popoActionMessage','正在继续发送…');try{const data=await request('/api/admin/popo/messages/'+encodeURIComponent(id)+'/resume',{method:'POST',body:JSON.stringify({confirmation:'确认从失败分段继续发送'})});text('popoActionMessage',data.message);await Promise.all([loadPopo(),showPopo(id)])}catch(error){setMessage('popoActionMessage',error.message,true)}finally{button.disabled=false}}
function statCard(label,value){const card=document.createElement('article');card.className='card';const name=document.createElement('span');name.className='label';name.textContent=label;const metric=document.createElement('div');metric.className='metric';metric.textContent=String(value);card.append(name,metric);return card}
function table(headers,rows){const value=document.createElement('table');const head=document.createElement('thead');const headRow=document.createElement('tr');headers.forEach(item=>{const cell=document.createElement('th');cell.textContent=item;headRow.appendChild(cell)});head.appendChild(headRow);const body=document.createElement('tbody');rows.forEach(row=>{const element=document.createElement('tr');row.forEach(item=>addCell(element,item));body.appendChild(element)});value.append(head,body);return value}
function statBlock(title,headers,rows){const card=document.createElement('article');card.className='card wide table-scroll';const heading=document.createElement('h2');heading.textContent=title;card.append(heading,table(headers,rows));return card}
function renderStats(data){statsData=data;const result=byId('statsResult');result.replaceChildren();const summary=document.createElement('div');summary.className='grid';summary.append(statCard('设计数量总计',data.total.quantity),statCard('工单条数',data.issueCount),statCard('AI 管线占比',data.total.aiRatio+'%'),statCard('人工占比',data.total.manualRatio+'%'));result.appendChild(summary);result.appendChild(statBlock('分类统计',['分类','设计数量','AI 数量','AI 占比','人工占比'],data.categories.map(item=>[item.category,item.quantity,item.aiQuantity,item.aiRatio+'%',item.manualRatio+'%'])));result.appendChild(statBlock('各游戏产品设计数量合计',['游戏产品','设计数量'],data.games.map(item=>[item.name,item.quantity])));result.appendChild(statBlock('各指派给设计数量合计',['指派给','设计数量','AI 占比'],data.assignees.map(item=>[item.name,item.stat.quantity,item.stat.aiRatio+'%'])));text('statsStatus',data.startDate&&data.endDate?data.startDate+' 至 '+data.endDate:'全部数据');byId('statsExport').disabled=false}
async function loadStats(){if(!token)return;const startDate=byId('statsStartDate').value;const endDate=byId('statsEndDate').value;const query=[startDate?'startDate='+encodeURIComponent(startDate):'',endDate?'endDate='+encodeURIComponent(endDate):''].filter(Boolean).join('&');try{renderStats(await request('/api/admin/stats'+(query?'?'+query:'')));text('statsMessage','统计完成')}catch(error){setMessage('statsMessage',error.message,true)}}
function exportStats(){if(!statsData)return;const lines=['工单统计','设计数量总计：'+statsData.total.quantity,'AI 管线占比：'+statsData.total.aiRatio+'%','人工占比：'+statsData.total.manualRatio+'%','','分类统计'];statsData.categories.forEach(item=>lines.push(item.category+'：'+item.quantity));lines.push('','各游戏产品设计数量合计');statsData.games.forEach(item=>lines.push(item.name+'：'+item.quantity));const blob=new Blob([lines.join('\\r\\n')],{type:'text/plain;charset=utf-8'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=(statsData.startDate&&statsData.endDate?statsData.startDate+'-'+statsData.endDate:'工单')+'统计.txt';link.click();URL.revokeObjectURL(link.href)}
async function inspection(path,body,buttonId,messageId){const button=byId(buttonId);button.disabled=true;setMessage(messageId,path.includes('preview')?'正在查询易协作工单，请稍候…':'正在提交请求…');try{const data=await request(path,{method:'POST',...(body?{body:JSON.stringify(body)}:{})});if(data.previewId){previewId=data.previewId;text('inspectionPreviewSummary','巡检工单 '+data.scanned+' 个，待完善项 '+data.violations.length+' 项');text('inspectionPreviewContent',data.message||'本次巡检未发现待发送内容。');byId('acceptanceSend').disabled=false}text(messageId,data.message||'操作已完成');await loadStatus()}catch(error){setMessage(messageId,error.message,true)}finally{button.disabled=buttonId==='acceptanceSend'?!previewId:false}}
async function loadReviewSettings(){if(!token)return;try{const data=await request('/api/admin/review-settings');byId('reviewEnabled').checked=data.reviewEnabled;byId('reviewProvider').value=data.reviewProvider;byId('reviewModelInput').value=data.reviewModel;byId('reviewMaxTokens').value=data.reviewMaxTokens;byId('reviewKnowledgeBase').value=data.reviewKnowledgeBase;byId('reviewNotificationEnabled').checked=data.reviewNotificationEnabled}catch(error){setMessage('reviewSettingsMessage',error.message,true)}}
async function saveReviewSettings(){const button=byId('saveReviewSettings');button.disabled=true;setMessage('reviewSettingsMessage','正在保存审核配置…');const body={reviewEnabled:byId('reviewEnabled').checked,reviewProvider:byId('reviewProvider').value.trim(),reviewModel:byId('reviewModelInput').value.trim(),reviewMaxTokens:Number(byId('reviewMaxTokens').value),reviewKnowledgeBase:byId('reviewKnowledgeBase').value,reviewNotificationEnabled:byId('reviewNotificationEnabled').checked};try{const data=await request('/api/admin/review-settings',{method:'POST',body:JSON.stringify(body)});text('reviewSettingsMessage',data.message);setTimeout(()=>location.reload(),700)}catch(error){setMessage('reviewSettingsMessage',error.message,true);button.disabled=false}}
async function saveRuntime(){const button=byId('saveSettings');button.disabled=true;try{const data=await request('/api/admin/settings',{method:'POST',body:JSON.stringify({scheduleEnabled:byId('scheduleEnabled').checked,automaticSendEnabled:byId('automaticSendEnabled').checked,webhookProcessingEnabled:byId('webhookProcessingEnabled').checked})});text('globalMessage',data.message);await loadStatus()}catch(error){setMessage('globalMessage',error.message,true)}finally{button.disabled=false}}
function activate(page){document.querySelectorAll('[data-page],.page').forEach(item=>item.classList.remove('active'));document.querySelector('[data-page="'+page+'"]').classList.add('active');byId(page).classList.add('active');if(page==='issues')loadIssues();if(page==='validation')loadIssueReviews();if(page==='stats')loadStats();if(page==='popo')loadPopo();if(page==='settings')loadReviewSettings()}
document.querySelectorAll('[data-page]').forEach(button=>button.onclick=()=>activate(button.dataset.page));
byId('saveToken').onclick=()=>{const value=byId('adminToken').value.trim();if(!value){setMessage('globalMessage','管理令牌不能为空',true);return}token=value;sessionStorage.setItem('workorderAdminToken',token);tokenView();loadStatus()};
byId('clearToken').onclick=()=>{token='';sessionStorage.removeItem('workorderAdminToken');tokenView();setMessage('globalMessage','管理令牌已清除')};
byId('issuesSync').onclick=syncIssues;byId('issuesReload').onclick=loadIssues;byId('reviewIssue').onclick=reviewIssue;byId('reviewReload').onclick=loadIssueReviews;byId('statsQuery').onclick=loadStats;byId('statsExport').onclick=exportStats;byId('saveSettings').onclick=saveRuntime;byId('saveReviewSettings').onclick=saveReviewSettings;byId('todayPreview').onclick=()=>inspection('/api/admin/preview-today',null,'todayPreview','quickActionMessage');byId('testSend').onclick=()=>inspection('/api/admin/test-notification',null,'testSend','quickActionMessage');byId('acceptancePreview').onclick=()=>inspection('/api/admin/acceptance-preview',{startDate:byId('startDate').value,endDate:byId('endDate').value},'acceptancePreview','actionMessage');byId('acceptanceSend').onclick=()=>inspection('/api/admin/acceptance-send',{previewId,confirmation:'确认发送正式巡检结果'},'acceptanceSend','actionMessage');
['issuesStartDate','issuesEndDate','statsStartDate','statsEndDate','startDate','endDate'].forEach(id=>byId(id).value=today);tokenView();
function mountDesktopBar(){const api=window.__TAURI__;if(!api||!api.window||typeof api.window.getCurrentWindow!=='function')return;const bar=document.querySelector('[data-desktop-bar]');bar.hidden=false;document.body.classList.add('has-desktop-bar');const appWindow=api.window.getCurrentWindow();const actions={minimize:()=>appWindow.minimize(),maximize:()=>appWindow.toggleMaximize(),close:()=>appWindow.close()};Object.entries(actions).forEach(([name,run])=>{const button=bar.querySelector('[data-window="'+name+'"]');if(button)button.onclick=()=>{void run()}})}
mountDesktopBar();if(token)loadStatus();else setMessage('globalMessage','请前往设置页输入管理令牌');
`
}
