/**
 * 官方插件（cordis 与 dsh-a 到 dsh-d）的简体中文说明。
 * 插件管理页在 zh-CN 语言下优先显示这里的中文说明，缺失时回退英文原文。
 */
export const OFFICIAL_A_D = {
  '@deepseek-ai/cordis-plugin-hmr': 'Cordis 热模块替换插件',
  '@deepseek-ai/cordis-plugin-loader': 'Cordis 插件加载器',
  '@deepseek-ai/cordis-plugin-timer': 'Cordis 定时器服务',
  'cordis:empty': 'Cordis 内置空插件',
  'cordis:include': 'Cordis 内置 include 插件',
  '@deepseek-ai/dsh-acp': '仅面向自动化的 Agent Client Protocol 服务器：通过 JSON-RPC stdio 驱动 DeepSeek Harness Agent',
  '@deepseek-ai/dsh-acp-app': 'dsh ACP 配置组合层：基于 dsh-base 的自动化 JSON-RPC stdio 与进程生命周期',
  '@deepseek-ai/dsh-agent': 'DeepSeek Harness 的 Agent 接口、注册表、发起人作用域与事件词汇',
  '@deepseek-ai/dsh-agent-default-model': 'Agent 各入口共享的默认模型选择',
  '@deepseek-ai/dsh-agent-instructions': '加载 AGENTS.md / CLAUDE.md 说明文件的工作区上下文加载器',
  '@deepseek-ai/dsh-agent-loop': 'DeepSeek Harness 的具体 Agent 循环插件',
  '@deepseek-ai/dsh-agent-loop-testkit': '测试具体 Agent 循环所需的共享前置挂载',
  '@deepseek-ai/dsh-agent-presets': '从 preset cordis.yml 文件组装的按会话 Agent 组合',
  '@deepseek-ai/dsh-agent-spine-demo': 'Agent 主干演示插件',
  '@deepseek-ai/dsh-agent-tool-presentation': 'Agent 平面呈现选择器：把单个 Agent 的工具组合为 PTC 模式、原生或两者',
  '@deepseek-ai/dsh-anonymous-user-id': 'DeepSeek Harness 遥测与反馈关联用的共享匿名用户身份',
  '@deepseek-ai/dsh-api-gateway': 'Typert Remote Host 调度器与客户端 API 端点',
  '@deepseek-ai/dsh-api-remotes': '按应用选择的 Host 能力组装的 Remote BFF',
  '@deepseek-ai/dsh-api-session-controller': 'Session Remote 命令、冷读取与实时控制传输',
  '@deepseek-ai/dsh-api-settings-controller': '设置域接口上的配置界面 Remote 所有者',
  '@deepseek-ai/dsh-api-workspace-controller': 'Workspace Remote 命令与重连安全的状态传输',
  '@deepseek-ai/dsh-app-boot': '应用入口共享的启动胶水：.env 加载、失败即响的 Loader 守卫、快照感知配置解析与 Loader 启动序列',
  '@deepseek-ai/dsh-atomic-write': '零依赖原子文件替换：独占创建随机后缀临时文件并携带调用方声明的权限重命名',
  '@deepseek-ai/dsh-attachment': 'DeepSeek Harness 的持久不可变附件存储接口',
  '@deepseek-ai/dsh-attachment-local': 'DSH_HOME 下私有的内容寻址附件存储',
  '@deepseek-ai/dsh-authorization': '授权接口（ctx.authorization）：由插件拥有的、通过与人类对话获取凭据的流程',
  '@deepseek-ai/dsh-base': 'dsh 核心共享配置组合层：基础配置的第一个补丁层，向空配置根插入核心插件行',
  '@deepseek-ai/dsh-bash-local': 'DeepSeek Harness bash 执行接口的本地子进程实现',
  '@deepseek-ai/dsh-bash-sandbox': 'DeepSeek Harness bash 执行接口的沙箱实现：每条命令都经 ctx.sandbox 约束，上报拒绝/执行结果事实',
  '@deepseek-ai/dsh-brand': 'DeepSeek Harness 的无状态品牌化原始类型',
  '@deepseek-ai/dsh-client-connection': '认证 RPC 传输、代际生命周期与浏览器夹具',
  '@deepseek-ai/dsh-client-hmr': '仅供开发的热重载驱动器：SSE 重建帧、失效/预取、经内置 Loader 条目交换 fiber',
  '@deepseek-ai/dsh-client-locale': '语言插件：Host 侧偏好、可扩展语言目录、浏览器回退与类型化内置字典',
  '@deepseek-ai/dsh-client-modules': '双面客户端模块系统：Node 侧组装 __DSH_BOOT__ 入口图；浏览器侧是内置 cordis Loader 消费的惰性 CJS 模块表',
  '@deepseek-ai/dsh-client-runtime': 'DeepSeek Harness 浏览器客户端运行时',
  '@deepseek-ai/dsh-client-schema-form': 'Web 客户端基于 JSON Schema 的表单渲染器',
  '@deepseek-ai/dsh-client-store': '无 React 的可观察与快照存储契约，共享 Zustand/Immer 引擎',
  '@deepseek-ai/dsh-client-test-runtime': 'jsdom 插槽测试运行时：真实 Cordis Context、SlotRegistry 与 UI 渲染器，附测试自有的会话/工作区替身',
  '@deepseek-ai/dsh-client-ui-agent-preset': 'Agent 预设界面：后续会话默认、当前会话席位与组合编辑器',
  '@deepseek-ai/dsh-client-ui-approval': '作用于 Remote Event 瀑布上的审批编辑器接管',
  '@deepseek-ai/dsh-client-ui-attachment': '对话输入、消息图片与轨迹图片插槽的动态附件呈现插件',
  '@deepseek-ai/dsh-client-ui-brand-official': 'Web 客户端侧栏插槽的 DeepSeek Harness 官方品牌占位',
  '@deepseek-ai/dsh-client-ui-chat': '聊天会话目标、节点定义、渲染器与详情界面',
  '@deepseek-ai/dsh-client-ui-commands': '客户端命令界面：全局目录缓存、“/”源、三种命令 UI 与 popupSelect 注册表',
  '@deepseek-ai/dsh-client-ui-conversation': '与目标无关的会话组装：外壳、编辑器、队列与视图导航',
  '@deepseek-ai/dsh-client-ui-cordis': 'Cordis 动态插件定义卡：带运行/停止开关的 cordis_define 工具行',
  '@deepseek-ai/dsh-client-ui-deliverables': 'Web 端产物文件轮次尾部与可点击的最终响应文件引用',
  '@deepseek-ai/dsh-client-ui-directory-picker-browse': '应用内目录浏览界面：渲染宿主列目录与创建原语的工作区目录流程所有者',
  '@deepseek-ai/dsh-client-ui-directory-picker-native': '原生目录选择界面：驱动宿主系统选择器的无渲染工作区目录流程占位',
  '@deepseek-ai/dsh-client-ui-goal': '会话目标界面：停靠在编辑器上方的 GoalBar，读取目标会话投影',
  '@deepseek-ai/dsh-client-ui-input-trigger': '输入触发器管线：“/”与“@”检测、候选菜单与选择路由',
  '@deepseek-ai/dsh-client-ui-jobs': '会话头后台任务列表：镜像 session/jobs 帧的实时注册表状态',
  '@deepseek-ai/dsh-client-ui-layout': '外壳插件：带拖拽手柄的三栏 AppFrame 与 ctx.layout 视图状态服务（导航 + 面板）',
  '@deepseek-ai/dsh-client-ui-message-feedback': '每条消息的反馈控件（挂到助手消息操作条），由 messageFeedback Host Remote 支持',
  '@deepseek-ai/dsh-client-ui-model-selection': '基于共享模型目录、Session 投影与 session.selectModel 的模型选择',
  '@deepseek-ai/dsh-client-ui-permission-presets': '权限界面：常规设置中的新会话默认与基于权限投影的当前会话 /permission 弹窗',
  '@deepseek-ai/dsh-client-ui-plan': '计划模式编辑器控件：基于计划投影与 /plan 命令通道的 conversation.input.plan 席位',
  '@deepseek-ai/dsh-client-ui-primitives': 'dsh Web UI 的纯 React 原子组件：控件、图标、Markdown 与 JSON 检查器（零 cordis）',
  '@deepseek-ai/dsh-client-ui-reference': '统一的 Web @file 与 @session 引用源',
  '@deepseek-ai/dsh-client-ui-renderer': '浏览器 UI 渲染器：React 插槽绑定、ctx.uiRenderer 与组装好的应用根',
  '@deepseek-ai/dsh-client-ui-session': '面向 React 的 Session Controller 适配器与会话级插槽',
  '@deepseek-ai/dsh-client-ui-settings': '设置域基础插件：设置命名空间作用域服务与规范设置插槽类型契约',
  '@deepseek-ai/dsh-client-ui-settings-general': '设置常规文案与产品引导插件：常规分区、外壳触发/头部内容、设置字典与版本化欢迎提示',
  '@deepseek-ai/dsh-client-ui-settings-models': '基于既有设置与凭据联表的模型设置与共享产品引导对话框',
  '@deepseek-ai/dsh-client-ui-settings-plugin-inventory': 'Web 插件设置中的只读 Cordis Loader 清单标签页',
  '@deepseek-ai/dsh-client-ui-settings-plugins': '带功能自有标签页与可配置宿主插件卡的插件设置分区',
  '@deepseek-ai/dsh-client-ui-sidebar': '侧栏插件：会话多级树、搜索、分组与状态圆点',
  '@deepseek-ai/dsh-client-ui-skill': 'Web 技能引用与专用技能工具行',
  '@deepseek-ai/dsh-client-ui-slots': '插槽注册表纯核心：SlotMap 声明合并、单一 register 组合 API、共享 props 类型与渲染器安装接口',
  '@deepseek-ai/dsh-client-ui-subagent': 'Subagent 会话目录、续接路由 UI 与“@”引用源',
  '@deepseek-ai/dsh-client-ui-theme': '主题插件：插件前调色板的 Host 引导、无 DOM 的明暗/系统主题运行时、--dsw-* 令牌样式与外观设置行',
  '@deepseek-ai/dsh-client-ui-tool': '客户端工具调用树渲染器与按工具的键控呈现插槽',
  '@deepseek-ai/dsh-client-ui-trajectory': '带交互式耗时概览的轨迹事件账本：注册进会话 ViewMap 的纯消费插件（无服务）',
  '@deepseek-ai/dsh-client-ui-user-questions': 'Web 端 ask_user_question 编辑器接管与计划评审呈现 UI',
  '@deepseek-ai/dsh-client-ui-workflow-run': 'dsh web 的持久工作流运行会话节点与嵌套成员展开',
  '@deepseek-ai/dsh-client-ui-workspace': '工作区选择器插件：注册进侧栏与空状态工作区插槽的 WorkspacePicker',
  '@deepseek-ai/dsh-client-web': 'Web 启动内核：静态模块表、Cordis 加载器、无框架启动页与 UI 渲染器交接',
  '@deepseek-ai/dsh-client-web-react': 'DeepSeek Harness Web 客户端的 React 绑定',
  '@deepseek-ai/dsh-cmdline': '从 dsh 启动器向任何注入 cmdlineArgs 的应用插件传递不可变命令行',
  '@deepseek-ai/dsh-code-runtime': 'DeepSeek Harness 的抽象代码执行接口（ctx.codeRuntime）',
  '@deepseek-ai/dsh-code-runtime-python': 'DeepSeek Harness 代码执行接口的 CPython 子进程实现',
  '@deepseek-ai/dsh-code-runtime-worker-thread': 'DeepSeek Harness 代码执行接口的工作线程实现',
  '@deepseek-ai/dsh-command-compact': '显式会话压缩的人类斜杠命令',
  '@deepseek-ai/dsh-command-feedback': '仅记日志的会话反馈生产者与人类斜杠命令',
  '@deepseek-ai/dsh-command-goal': '持久同会话目标的人类斜杠命令',
  '@deepseek-ai/dsh-commands': 'DeepSeek Harness UI 的插件拥有的人类命令注册表',
  '@deepseek-ai/dsh-compaction': 'DeepSeek Harness 的抽象压缩服务接口（ctx.compaction）',
  '@deepseek-ai/dsh-compaction-basic': 'DeepSeek Harness 基于令牌计量的压缩策略与 LLM 摘要后端',
  '@deepseek-ai/dsh-compaction-tool-result-pruner': '对工具结果表面节点做可回放、无模型的头/中/尾裁剪',
  '@deepseek-ai/dsh-cordis-client-runner': '动态双半插件的浏览器半边：事件订阅、闭包求值、守卫门面与加载器条目',
  '@deepseek-ai/dsh-cordis-host-runner': '动态包定义注册表、宿主半边沙箱生命周期与模型挂载双半包的调用处理器表',
  '@deepseek-ai/dsh-credentials': '抽象凭据接口（ctx.credentials）：设置保存密钥引用，提供方持有值',
  '@deepseek-ai/dsh-credentials-local': 'DeepSeek Harness 的文件凭据提供方（实时进程环境下的 $DSH_HOME/.env）',
  '@deepseek-ai/dsh-deepseek-llm-api-extensions': '官方 DeepSeek LLM API 适配器的附加请求字段注册表',
} as const
