/**
 * 官方插件（dsh-m 到 dsh-s）的简体中文说明。
 * 插件管理页在 zh-CN 语言下优先显示这里的中文说明，缺失时回退英文原文。
 */
export const OFFICIAL_M_S = {
  '@deepseek-ai/dsh-mcp-client': 'MCP 客户端桥：连接 MCP 服务器并将其工具注册到 ctx.tools',
  '@deepseek-ai/dsh-message-feedback': 'DeepSeek Harness 的随生命周期绑定每条消息评分与备注侧栏',
  '@deepseek-ai/dsh-native-command': '宿主原生命令与路径打开工具：免 shell 执行、取消、桌面检测与 WSL 交接',
  '@deepseek-ai/dsh-output-retention': '零依赖边界保留原语：ItemRetainer/TextRetainer 与中性提示助手（保留了什么、省略了什么）',
  '@deepseek-ai/dsh-permission-presets': 'DeepSeek Harness 面向用户的权限预设（ctx.permissionPresets）：一个产品级权限选择器捆绑沙箱模式与审批策略旋钮，写入各自的会话事件',
  '@deepseek-ai/dsh-persona': 'DeepSeek Harness 的组合编写的部署人设分区',
  '@deepseek-ai/dsh-plan-mode': '带部署指引、直接斜杠命令与用户评审退出的按 Agent 记日志计划模式',
  '@deepseek-ai/dsh-plugin-package-inventory-deepseek': '官方 DeepSeek LLM API 请求的活动 Loader 支持插件包清单',
  '@deepseek-ai/dsh-pwsh-local': 'DeepSeek Harness bash 执行接口的本地 PowerShell 实现',
  '@deepseek-ai/dsh-pwsh-sandbox': 'DeepSeek Harness PowerShell 执行接口的沙箱实现：每条命令都经 ctx.sandbox 约束，上报拒绝/执行结果事实',
  '@deepseek-ai/dsh-repeat-tool-reminder': '重复工具调用守卫插件：Agent 在相同工具调用上循环时给出建议提醒',
  '@deepseek-ai/dsh-sandbox': 'DeepSeek Harness 的抽象进程沙箱接口（ctx.sandbox）：同世界约束词汇与 SandboxProvider 契约',
  '@deepseek-ai/dsh-sandbox-local': 'DeepSeek Harness 沙箱接口的本地进程后端：bwrap、npm 分发的 landlock-run 启动器、macOS Seatbelt 或 Windows ACL 受限令牌运行器，功能探测、失败即关',
  '@deepseek-ai/dsh-sandbox-policy': '每次调用沙箱策略解析器与当前模型上下文：部署回退加每个会话的模式与工作区根，被每个执行能力族共享',
  '@deepseek-ai/dsh-sandbox-windows-acl': 'DeepSeek Harness 沙箱接口的 Windows ACL 写限制后端（带能力 SID 写白名单的受限令牌启动）',
  '@deepseek-ai/dsh-schedule': 'Agent 作用域的持久 after、at 与固定频率提醒（基于会话事件日志）',
  '@deepseek-ai/dsh-scope': '作用域上下文注册原语（作用域标签、作用域过滤事件分发）',
  '@deepseek-ai/dsh-sdk-app': 'dsh SDK 配置组合层：基于 dsh-base 的 stdio JSON-RPC 服务与进程生命周期',
  '@deepseek-ai/dsh-sdk-client': '驱动 DeepSeek Harness 运行时子进程（stdio JSON-RPC）的 TypeScript 客户端 SDK：高层 DeepSeekHarness turns API 与低层 HarnessClient',
  '@deepseek-ai/dsh-sdk-jsonrpc-server': '面向进程外 DeepSeek Harness SDK 客户端的 stdio JSON-RPC 服务器插件',
  '@deepseek-ai/dsh-sdk-minimal': '独立最小 SDK 配置组合层：JSON-RPC、一个 DeepSeek 适配器、持久终端、编辑器与 JSONL 会话',
  '@deepseek-ai/dsh-sdk-protocol': 'DeepSeek Harness SDK 运行时的共享线协议：换行分隔 JSON-RPC stdio 传输与运行时服务器、SDK 客户端之间使用的命名请求/结果/通知类型',
  '@deepseek-ai/dsh-session': 'DeepSeek Harness 的事件溯源会话存储',
  '@deepseek-ai/dsh-session-checkpoint-policy': '模型请求与工具副作用前的语义会话持久化检查点',
  '@deepseek-ai/dsh-session-log-deepseek': '官方 DeepSeek LLM API 的增量无损会话日志请求扩展',
  '@deepseek-ai/dsh-session-log-export': 'Web 会话日志导出命令与共享下载对话框',
  '@deepseek-ai/dsh-session-persistence': 'DeepSeek Harness 的抽象持久会话存储接口（ctx.sessionPersistence）',
  '@deepseek-ai/dsh-session-persistence-jsonl': 'DeepSeek Harness 的 JSONL 持久会话存储后端',
  '@deepseek-ai/dsh-session-persistence-sqlite': 'SQLite 会话持久化',
  '@deepseek-ai/dsh-session-projection': '会话投影接口：可合并扩展的投影类型表、提供方契约与 ctx.sessionProjections 注册表，提供日志派生的按会话状态当前值',
  '@deepseek-ai/dsh-session-projection-cache': '持久化投影缓存（ctx.sessionProjectionCache）：session_projcache 存储域上的持久按会话检查点记录（逐条布局）、节流写后与缓存列表读取',
  '@deepseek-ai/dsh-session-query': '组合会话查询服务契约：具体读取、追踪与过滤器',
  '@deepseek-ai/dsh-session-query-sqlite': '带 SQLite FTS5 搜索的 ctx.sessionQuery 具体后端',
  '@deepseek-ai/dsh-session-reference': '跨会话快照引用与持久不可信模型上下文（ctx.sessionReferenceResolver）',
  '@deepseek-ai/dsh-session-snapshot': '会话日志快照核心：ACP 协议适配器、期望输出规范化与夹具不变式',
  '@deepseek-ai/dsh-session-stats': '全日志对话计数与墙钟时间投影（sessionStats）',
  '@deepseek-ai/dsh-session-telemetry': 'DeepSeek Harness 的 SessionTelemetryBackend 接口：会话事件捕获、投影、脱敏与上报后端交接',
  '@deepseek-ai/dsh-session-telemetry-otel': 'DeepSeek Harness 遥测接口的 OpenTelemetry 后端：把捕获的会话记录交给 OTel JS SDK 日志管线',
  '@deepseek-ai/dsh-session-title': 'DeepSeek Harness 的日志支持会话标题服务与提供方注册表',
  '@deepseek-ai/dsh-session-title-all-prompts-llm': 'DeepSeek Harness 会话标题的全用户消息 LLM 提供方插件',
  '@deepseek-ai/dsh-session-title-first-prompt-llm': 'DeepSeek Harness 会话标题的首条消息 LLM 提供方插件',
  '@deepseek-ai/dsh-session-title-llm': 'DeepSeek Harness 会话标题提供方的共享 LLM 生成策略',
  '@deepseek-ai/dsh-settings': 'DeepSeek Harness 的抽象用户设置接口（ctx.settings）',
  '@deepseek-ai/dsh-settings-file': 'DeepSeek Harness 的文件设置提供方（settings.yaml）',
  '@deepseek-ai/dsh-shell': 'DeepSeek Harness 的抽象 bash 执行接口（ctx.shell）',
  '@deepseek-ai/dsh-shell-env': '与工具无关的受管 DSH_* 终端环境注册表',
  '@deepseek-ai/dsh-skill': 'DeepSeek Harness 的 Agent 技能提供方注册表',
  '@deepseek-ai/dsh-skill-badge': 'DeepSeek Harness 的内置 dsh badge 技能提供方',
  '@deepseek-ai/dsh-skill-filesystem': 'DeepSeek Harness 的本地文件系统技能提供方',
  '@deepseek-ai/dsh-spill': 'DeepSeek Harness 的抽象溢出存储接口（ctx.spillStore）：保存超大工具文本并返回检索定位符',
  '@deepseek-ai/dsh-spill-local': 'DeepSeek Harness 溢出存储接口的本地文件系统实现（私有会话级文件）',
  '@deepseek-ai/dsh-spill-policy': 'DeepSeek Harness 的工具结果溢出策略：用保留预览加溢出文件路径替换超大纯文本工具结果（无服务 API）',
  '@deepseek-ai/dsh-storage': 'DeepSeek Harness 的存储枢纽（ctx.storage）：命名后端注册表加挂载的数据形式设施',
  '@deepseek-ai/dsh-storage-domain': '域数据形式（ctx.storage.domain）：基于存储后端的模式校验、发事件 KV 域',
  '@deepseek-ai/dsh-storage-json': 'DeepSeek Harness 存储枢纽的 JSON 文件 KV 后端',
  '@deepseek-ai/dsh-storage-sqlite': 'DeepSeek Harness 存储枢纽的 SQLite 后端（kv 面）',
  '@deepseek-ai/dsh-subagent': '抽象 Subagent 接口（ctx.subagents）：委托子 Agent 的命名提供方注册表',
  '@deepseek-ai/dsh-subagent-acp': '进程外 ACP Subagent 后端：在生成的子进程中通过 Agent Client Protocol 驱动子 Agent',
  '@deepseek-ai/dsh-subagent-claude-code': '基于官方 Agent SDK 的一次性 Claude Code Subagent 提供方',
  '@deepseek-ai/dsh-subagent-codex': '基于官方 app-server 协议的一次性 Codex Subagent 提供方',
  '@deepseek-ai/dsh-subagent-dsh-sdk': '进程外 SDK Subagent 后端：通过 TypeScript SDK 客户端以 stdio JSON-RPC 驱动子 DeepSeek Harness 运行时子进程',
  '@deepseek-ai/dsh-subagent-fork-in-process': '进程内 fork Subagent 后端：以父日志前缀种子运行子 Agent',
  '@deepseek-ai/dsh-subagent-in-process-driver': '共享的进程内 Subagent 运行驱动器：在 ctx.agents 上驱动子 Agent（供 spawn 与 fork 后端使用）',
  '@deepseek-ai/dsh-subagent-spawn-in-process': '进程内 spawn Subagent 后端：在 ctx.agents 上运行全新子 Agent',
  '@deepseek-ai/dsh-subprocess': 'DeepSeek Harness 的子进程接口（ctx.subprocess）：受管进程组、有界溢出输出与升级式终止，统一在一个抽象服务后',
  '@deepseek-ai/dsh-subprocess-e2b': 'DeepSeek Harness 的 E2B 子进程实现',
  '@deepseek-ai/dsh-subprocess-local': 'DeepSeek Harness 子进程接口的本地子进程实现',
} as const
