import { describe, expect, it } from 'vitest'
import { controlPanelNavigationScript, injectControlPanelNavigation } from '../../src/harness/navigation.js'
import { adminPage } from '../../src/plugins/admin/page.js'

const sections = ['业务总览', '工单', 'Webhook 事件', '复核结果', '巡检发送', '设置']

describe('Harness 工单控制面', () => {
  it('提供完整业务导航和受控发送入口', () => {
    const page = adminPage()
    sections.forEach((section) => expect(page).toContain(section))
    expect(page).toContain('确认发送正式巡检结果')
    expect(page).toContain('/api/admin/acceptance-preview')
    expect(page).toContain('保存到当前会话')
    expect(page).toContain('webhookProcessingEnabled')
    expect(page).toContain('页面仅显示是否已配置，不返回明文')
    expect(page).not.toContain("prompt('请输入管理令牌')")
    expect(page).not.toContain('body.insertRow()')
    expect(page).toContain("document.createElement('tr')")
    expect(page).toContain('quickActionMessage')
    expect(page).toContain('正在查询易协作工单，请稍候')
    expect(page).toContain('巡检工单数')
    expect(page).toContain('待完善项数')
    expect(page).toContain("'巡检工单 '+data.scanned+' 个")
    expect(page).not.toContain("'扫描 '+data.scanned+' 张")
    expect(page).toContain("button.textContent='处理中…'")
    expect(page).toContain('id="previewContent"')
    expect(page).toContain('height:320px;overflow:auto')
    expect(page).not.toContain('id="previewId"')
    expect(page).not.toContain('<th>预览标识</th>')
    expect(page).toContain('查看详情')
    expect(page).toContain('/api/admin/issues')
    expect(page).toContain('id="issueRows"')
    expect(page).toContain('投放渠道')
    expect(page).toContain('完成日期')
    expect(page).toContain('/api/admin/previews/')
    expect(page).toContain('id="reviewDetailContent"')
    expect(page).toContain('id="reviewRows"')
    expect(page).toContain("row.onclick=()=>loadReviewDetail")
    expect(page).toContain("button.textContent='加载中…'")
    expect(page).toContain("resend.textContent='再次发送'")
    expect(page).toContain("confirm('确认再次发送该复核结果至 POPO？')")
    expect(page).toContain('/resend')
    expect(page).toContain('reviewActionMessage')
    expect(page).toContain("link.target='_blank'")
    expect(page).toContain("link.rel='noopener noreferrer'")
    expect(page).not.toContain('<tbody id="reviews">')
    expect(page).not.toContain('😀')
    expect(page).toContain('返回主页面')
    expect(page).toContain('href="/"')
    expect(page).toContain('data-desktop-bar')
    expect(page).toContain('data-tauri-drag-region')
    expect(page).toContain('data-window="minimize"')
    expect(page).toContain('has-desktop-bar')
    expect(page).toContain('window.__TAURI__')
    expect(page).toContain('appWindow.toggleMaximize()')
    expect(page).toContain('data-page="stats"')
    expect(page).toContain('数据统计')
    expect(page).toContain('id="statsResult"')
    expect(page).toContain('id="statsQuery"')
    expect(page).toContain('id="statsExport"')
    expect(page).toContain('导出 TXT')
    expect(page).toContain('/api/admin/stats')
    expect(page).toContain('statsStartDate')
    expect(page).toContain('按工单「期望交付时间」筛选')
    expect(page).toContain('总单 分类不纳入统计')
    expect(page).toContain('AI 管线占比')
    expect(page).toContain('各游戏产品设计数量合计')
    expect(page).toContain('各指派给设计数量合计')
    expect(page).toContain('【所有项目设计数量总计】')
    expect(page).toContain('AI管线占比 ')
    const script = page.match(/<script>([\s\S]*)<\/script>/)?.[1]
    expect(script).toBeTruthy()
    expect(() => new Function(script ?? '')).not.toThrow()
  })

  it('通过官方索引扩展挂入侧边栏设置区域', () => {
    const script = controlPanelNavigationScript()
    expect(script).not.toContain('</script')
    expect(script).toContain("querySelector('[class*=settingsArea]')")
    expect(script).toContain("const path='/workorder-agent'")
    const html = injectControlPanelNavigation('<html><body><main></main></body></html>')
    expect(html).toContain('data-workorder-navigation')
    expect(html).toContain("const path='/workorder-agent'")
  })
})
